steps:
  - label: ":mag: lint"
    command: |
      curl -LsSf https://astral.sh/uv/install.sh | sh
      export PATH="$HOME/.local/bin:$PATH"
      uv tool install rust-just
      uv sync --frozen
      just lint
